import { Geist, Geist_Mono } from "next/font/google";
import Navbar from './components/Navbar';
import "../app/globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>
        <Navbar />
        <main className="pl-0 md:pl-60 w-full transition-all duration-300 ease-in-out">
          <div className="p-4 md:p-8">
            {children}
          </div>
        </main>
      </body>
    </html>
  );
}

